language: python

python:
  - '3.3'
  - '3.4'

install:
  - pip install colorama
  - python setup.py install

script:
  - run-contexts -v

deploy:
  provider: pypi
  user: benjamin.hodgson
  password:
    secure: ZQlfUvD9D1CXLsYaXJb0Gg4PgcUPhDe2NGZY0CemQv7iTLfvjlUCPQS8ODofuzO7VwjCamrN6Iwe+w8216nBK8K03XqrB57tif/5FUJ9asDWjqJHRvIJgB/ad5Oi8b1ShMY5XRRLjLGB9c1oeHATjzPcC/c5NJ6COeZ1gbfwvv4=
  on:
    tags: true
